import type { Drug, Location, LocationId } from './types';

// ---------------------------------------------------------------------------
// Static reference data. The original NYC drug/location set (see BRIEF.md §3).
// Drug price ranges and economy constants live in economy.ts; runtime prices are
// generated by the engine (engine/market.ts).
// ---------------------------------------------------------------------------

export const DRUGS: Drug[] = [
  { id: 'cocaine', name: 'Cocaine' },
  { id: 'hashish', name: 'Hashish' },
  { id: 'heroin', name: 'Heroin' },
  { id: 'ecstasy', name: 'Ecstasy' },
  { id: 'smack', name: 'Smack' },
  { id: 'opium', name: 'Opium' },
  { id: 'crack', name: 'Crack' },
  { id: 'peyote', name: 'Peyote' },
  { id: 'shrooms', name: 'Shrooms' },
  { id: 'speed', name: 'Speed' },
  { id: 'weed', name: 'Weed' },
];

export const DRUG_NAME: Record<string, string> = Object.fromEntries(
  DRUGS.map((d) => [d.id, d.name]),
);

// Subway grid order matches the screenshot:
//   Bronx        Manhattan
//   Ghetto       Coney Island
//   Central Park Brooklyn
export const LOCATIONS: Location[] = [
  { id: 'bronx', name: 'Bronx' },
  { id: 'manhattan', name: 'Manhattan' },
  { id: 'ghetto', name: 'Ghetto' },
  { id: 'coney-island', name: 'Coney Island' },
  { id: 'central-park', name: 'Central Park' },
  { id: 'brooklyn', name: 'Brooklyn' },
];

export const LOCATION_NAME: Record<LocationId, string> = Object.fromEntries(
  LOCATIONS.map((l) => [l.id, l.name]),
) as Record<LocationId, string>;
